name = "meganspurney-phd-portfolio"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".svelte-kit/output/client"

[build]
command = "npm run build"

[env.production]
compatibility_flags = ["nodejs_compat"]